### ISSUE TITLE
Completed module 1 assignments

### ISSUE THREAD

**Issue by AaronKip-42** [ds4owd/md-01-assignments#2]
Done; @larnsce @mianzg @sskorik01

**Comment by larnsce** [comment]
Hi Aaron, thanks for letting us know. I have checked on Posit Cloud, but could not find your repository. The one you opened this issue on is the template. From the template I created the following for you:

- https://github.com/ds4owd-001/md-01-assignments-AaronKip-42

Please clone that one to Posit Cloud and ensure that you do it to the workspace for the course:

- https://posit.cloud/spaces/426916/content/all?sort=name_asc

Did you get your GitHub Personl Access Token from Step 1 of Assignment 3? If not, start from Step 1, otherwise continue from Step 2:

- https://ds4owd-001.github.io/website/assignments/md-01/am-01-3-github.html

**Comment by AaronKip-42** [comment]
1. Please clone that one to Posit Cloud and ensure that you do it to the workspace for the course:

https://posit.cloud/spaces/426916/content/all?sort=name_asc

-  I tried to open this link but i got this response **_''Sorry, but you do not have access'._** 

2. i have followed other instructions keenly , kindly check if you can find my repository on posit cloud;  @larnsce @mianzg @sskorik01

**Comment by larnsce** [comment]
I will close the issue here. Please continue communication here: https://github.com/ds4owd-001/md-01-assignments-AaronKip-42/issues/2
